


a=("asdfas\tdfa\tsdf")
seq="+"
print(a.capitalize())
print(a.center(30))  
print(a.count("d"))
print(a.encode(encoding='UTF-8',errors='strict'))
print(a.endswith("f"))
print(a.find("e",5))
#print(a.index("e"))报异常
print(a.isalnum())
print(a.isalpha())
print(a.isdigit())
print(a.islower())
print(a.isnumeric())
print(a.isspace())
print(a.istitle())
print(seq.join(a)) #  有问题
print(len(a))
print(a.ljust(30,"-"))
print(a.lower())
print(a.lstrip())
print(min(a))
print(max(a))
print(a.replace("F","e"))
print(a.rfind("f"))
print(a.rindex("f"))
print(a.rjust(40,"+"))
print(a.rstrip())
print(a.split("f"))
print(a.splitlines(True))
print(a.rfind("f"))
print(a.startswith("e"))
print(a.strip())
print(a.swapcase())
print(a.upper())
print(a.isdecimal())
print(a.split("s",1))
print(a.expandtabs())
